name: Build & Test

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2

    - name: Install ninja
      run: sudo apt-get update && sudo apt-get install ninja-build

    - name: Create Build Environment
      run: cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{runner.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -G "Ninja Multi-Config" -B ${{runner.workspace}}/build  

    - name: Build
      shell: bash
      run: ninja -j12 -C ${{runner.workspace}}/build

    - name: Test
      working-directory: ${{runner.workspace}}/build
      shell: bash
      run: ctest -j12 -C Debug
